#!/bin/bash
if ls okaitslinblog.github.io > /dev/null 2>&1
  then
  true
  else
  gh repo clone okaitslinblog/okaitslinblog.github.io
fi
if ls img/* > /dev/null 2>&1
  then
  mv img/* okaitslinblog.github.io/img/
fi
mv $1 okaitslinblog.github.io/_posts/
cd okaitslinblog.github.io
ls
echo "アップロード処理を開始します。"
git add .
git commit -m "[add] Post"
gh pr create --title "[add] Post" --body "Automaticaly generated by blogwriter"
echo "Done."
