#!/bin/bash
if ls linuxcodevblog > /dev/null 2>&1
  then
  true
  else
  gh repo clone linuxcodevserver/linuxcodevblog
fi
if ls img/* > /dev/null 2>&1
  then
  mv img/* linuxcodevblog/img/
fi
mv $1 linuxcodevblog/_posts/
cd linuxcodevblog
ls
echo "アップロード処理を開始します。"
git add .
git commit -m "[add] Post"
gh pr create --title "[add] Post" --body "Automaticaly generated by blogwriter"
echo "Done."
